// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starlights.Modules.Elements.Data.EntityFramework;

#nullable disable

namespace Starlights.Modules.Elements.Data.EntityFramework.Migrations
{
    [DbContext(typeof(ElementsContext))]
    [Migration("20250923181831_AddOrderSequence")]
    partial class AddOrderSequence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("elements")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SystemIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("system_identifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("element", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.ElementComponentBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("OrderSequence")
                        .HasColumnType("int")
                        .HasColumnName("component_order_sequence");

                    b.Property<Guid>("OwningElement")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owning_element_id");

                    b.HasKey("Id");

                    b.HasIndex("OwningElement", "OrderSequence")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.AbbreviationComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("abbreviation");

                    b.ToTable("element_component_abbreviation", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.AbilityComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abbreviation");

                    b.ToTable("element_component_ability", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.DescriptionComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.ToTable("element_component_description", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.IncludeRuleComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<Guid>("IncludeElement")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("include_element_id");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int")
                        .HasColumnName("level_requirement");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.ToTable("element_component_include_rule", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.LanguageComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("origin");

                    b.ToTable("element_component_language", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.PrerequisitesComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("prerequisites");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.ToTable("element_component_prerequisites", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.PrimaryAbilityComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<Guid>("PrimaryAbility")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("primary_ability_id");

                    b.ToTable("element_component_primary_ability", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.SelectionRuleComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("element_type");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit")
                        .HasColumnName("is_optional");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int")
                        .HasColumnName("level_requirement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RangeSupports")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("range_supports");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("short_description");

                    b.Property<string>("Supports")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supports");

                    b.ToTable("element_component_selection_rule", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.ShortDescriptionComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.ToTable("element_component_short_description", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.SortingComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<double>("SortingOrder")
                        .HasColumnType("float")
                        .HasColumnName("sorting_order");

                    b.ToTable("element_component_sorting", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.StatisticRuleComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int")
                        .HasColumnName("level_requirement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.Property<string>("StackingBonus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stacking_bonus");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.ToTable("element_component_statistic_rule", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.ElementComponentBase", b =>
                {
                    b.HasOne("Starlights.Modules.Elements.Domain.Element", null)
                        .WithMany("Components")
                        .HasForeignKey("OwningElement")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Element", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
