// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starlights.Modules.Elements.Data.EntityFramework;

#nullable disable

namespace Starlights.Modules.Elements.Data.EntityFramework.Migrations
{
    [DbContext(typeof(ElementsContext))]
    [Migration("20260104203617_AddSpellcastingAspects")]
    partial class AddSpellcastingAspects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("elements")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SystemIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("system_identifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("element", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.ElementComponentBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("OrderSequence")
                        .HasColumnType("int")
                        .HasColumnName("component_order_sequence");

                    b.Property<Guid>("OwningElement")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owning_element_id");

                    b.HasKey("Id");

                    b.HasIndex("OwningElement", "OrderSequence")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Starlights.Platform.Components.Data.EntityFramework.EventMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("event_messages", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.AbbreviationComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("abbreviation");

                    b.ToTable("element_component_abbreviation", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.AbilityComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abbreviation");

                    b.ToTable("element_component_ability", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.ClassificationsComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("_labels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("labels");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tags");

                    b.ToTable("element_component_classifications", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.DescriptionComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.ToTable("element_component_description", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.FeatAttributesComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.ToTable("element_component_feat_attributes", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.IncludeRuleComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IncludeElement")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("include_element_id");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int")
                        .HasColumnName("level_requirement");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.ToTable("element_component_include_rule", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.LanguageComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("origin");

                    b.ToTable("element_component_language", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.PrerequisitesComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("prerequisites");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.ToTable("element_component_prerequisites", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.PrimaryAbilityComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<Guid>("PrimaryAbility")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("primary_ability_id");

                    b.ToTable("element_component_primary_ability", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.ProficiencyAttributesComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("ProficiencyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("proficiency_type");

                    b.ToTable("element_component_proficiency_attributes", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.RepeatableComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("bit")
                        .HasColumnName("is_repeatable");

                    b.ToTable("element_component_repeatable", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.SelectionRuleComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("element_type");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit")
                        .HasColumnName("is_optional");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int")
                        .HasColumnName("level_requirement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RangeSupports")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("range_supports");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("short_description");

                    b.Property<string>("Supports")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supports");

                    b.ToTable("element_component_selection_rule", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.ShortDescriptionComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.ToTable("element_component_short_description", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.SortingComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<double>("SortingOrder")
                        .HasColumnType("float")
                        .HasColumnName("sorting_order");

                    b.ToTable("element_component_sorting", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.SpellcastingAspects", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("casting_time");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("components");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("range");

                    b.ToTable("element_component_aspects_spellcasting", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.StatisticRuleComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int")
                        .HasColumnName("level_requirement");

                    b.Property<int?>("Maximum")
                        .HasColumnType("int")
                        .HasColumnName("maximum");

                    b.Property<int?>("Minimum")
                        .HasColumnType("int")
                        .HasColumnName("minimum");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirements");

                    b.Property<string>("StackingBonus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stacking_bonus");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.ToTable("element_component_statistic_rule", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.SupportsComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("_supports")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("supports");

                    b.ToTable("element_component_supports", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.ElementComponentBase", b =>
                {
                    b.HasOne("Starlights.Modules.Elements.Domain.Element", null)
                        .WithMany("Components")
                        .HasForeignKey("OwningElement")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Element", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
