// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starlights.Modules.Elements.Data.EntityFramework;

#nullable disable

namespace Starlights.Modules.Elements.Data.EntityFramework.Migrations
{
    [DbContext(typeof(ElementsContext))]
    partial class ElementsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("elements")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("element", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.ElementComponentBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwningElement")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwningElement");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.AbbreviationComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.ToTable("element_component_abbreviation", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.AbilityComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("element_component_ability", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.DescriptionComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("element_component_description", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.IncludeRuleComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<Guid>("IncludeElement")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int");

                    b.ToTable("element_component_include_rule", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.LanguageComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.ToTable("element_component_language", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.PrerequisitesComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Prerequisites")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.ToTable("element_component_prerequisites", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.PrimaryAbilityComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<Guid>("PrimaryAbility")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("element_component_primary_ability", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.ShortDescriptionComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("element_component_short_description", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Components.SortingComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Elements.Domain.ElementComponentBase");

                    b.Property<double>("SortingOrder")
                        .HasColumnType("float");

                    b.ToTable("element_component_sorting", "elements");
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.ElementComponentBase", b =>
                {
                    b.HasOne("Starlights.Modules.Elements.Domain.Element", null)
                        .WithMany("Components")
                        .HasForeignKey("OwningElement")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Elements.Domain.Element", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
