using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Starlights.Platform.SourceGenerators;

[Generator]
public class EntityIdSourceGenerator : IIncrementalGenerator
{
    public const string EntityAttributeFullName = "Starlights.Platform.SourceGenerators.Entities.Attributes.EntityAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter to classes that have Entity attribute
        var entityClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: EntityAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (context, _) => GetEntityInfo(context))
            .Where(static entityInfo => entityInfo is not null);

        // Generate the EntityId structs
        context.RegisterSourceOutput(entityClasses.Collect(), static (context, entityInfos) =>
        {
            foreach (var entityInfo in entityInfos)
            {
                if (entityInfo is null)
                {
                    continue;
                }

                var source = GenerateEntityIdStruct(entityInfo);
                context.AddSource($"{entityInfo.IdTypeName}.g.cs", source);
            }
        });
    }

    private static EntityInfo? GetEntityInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetNode is not ClassDeclarationSyntax)
        {
            return null;
        }

        if (context.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        var className = symbol.Name;
        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        var idTypeName = $"{className}Id";

        return new EntityInfo(className, namespaceName, idTypeName);
    }

    private static string GenerateEntityIdStruct(EntityInfo entityInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(entityInfo.Namespace))
        {
            sb.AppendLine($"namespace {entityInfo.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Represents a unique identifier for {entityInfo.EntityName} entities.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[DebuggerDisplay(\"{Value}\")]");
        sb.AppendLine($"public readonly record struct {entityInfo.IdTypeName}(Guid Value)");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Creates a new {entityInfo.IdTypeName} with a Version 7 GUID.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static {entityInfo.IdTypeName} New() => new(Guid.CreateVersion7());");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Implicitly converts {entityInfo.IdTypeName} to Guid.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static implicit operator Guid({entityInfo.IdTypeName} id) => id.Value;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private class EntityInfo
    {
        public EntityInfo(string entityName, string namespaceName, string idTypeName)
        {
            EntityName = entityName;
            Namespace = namespaceName;
            IdTypeName = idTypeName;
        }

        public string EntityName { get; }
        public string Namespace { get; }
        public string IdTypeName { get; }
    }
}