// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starlights.Modules.Characters.Data.EntityFramework;

#nullable disable

namespace Starlights.Modules.Characters.Data.EntityFramework.Migrations
{
    [DbContext(typeof(CharactersContext))]
    [Migration("20250806164901_AddEventMessage")]
    partial class AddEventMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("characters")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Appearance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PortraitUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("appearance", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("character", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssociatedElementName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("registration", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationIncludeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedIncludeRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IncludedElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IncludedElementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("registration_include_rules", "characters");
                });

            modelBuilder.Entity("Starlights.Platform.Components.Data.EntityFramework.EventMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EventMessage", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationIncludeRule", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Registrations.Registration", null)
                        .WithMany("IncludeRules")
                        .HasForeignKey("RegistrationId");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.Registration", b =>
                {
                    b.Navigation("IncludeRules");
                });
#pragma warning restore 612, 618
        }
    }
}
