// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starlights.Modules.Characters.Data.EntityFramework;

#nullable disable

namespace Starlights.Modules.Characters.Data.EntityFramework.Migrations
{
    [DbContext(typeof(CharactersContext))]
    [Migration("20251010201121_AddProgressionOrigin")]
    partial class AddProgressionOrigin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("characters")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Abilities.AbilityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abbreviation");

                    b.Property<int>("AdditionalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("additional_score");

                    b.Property<Guid>("AssociatedRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_registration_id");

                    b.Property<int>("BaseScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("base_score");

                    b.Property<int>("CalculatedModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("calculated_modifier");

                    b.Property<int>("CalculatedScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("calculated_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("parent_component_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedRegistrationId");

                    b.HasIndex("parent_component_id");

                    b.ToTable("ability_scores", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("character", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Classes.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("Registration")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("parent_component_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Registration");

                    b.HasIndex("parent_component_id");

                    b.ToTable("character_class", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ParentCharacter")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_character");

                    b.HasKey("Id");

                    b.HasIndex("ParentCharacter");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociatedElementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_element_id");

                    b.Property<string>("AssociatedElementName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("associated_element_name");

                    b.Property<string>("AssociatedElementType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("associated_element_type");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("character_id");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_registration_id");

                    b.Property<Guid?>("ProgressionOriginRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("progression_origin_registration_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("registration", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationIncludeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociatedIncludeRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_include_rule_id");

                    b.Property<Guid>("IncludedElementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("included_element_id");

                    b.Property<string>("IncludedElementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("included_element_name");

                    b.Property<Guid>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_registration_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegistrationId");

                    b.ToTable("registration_include_rules", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationSelectionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociatedSelectionRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_selection_rule_id");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("element_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_registration_id");

                    b.Property<Guid?>("SelectedOption")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_selection");

                    b.Property<Guid?>("SelectionRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_selection_registration_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegistrationId");

                    b.ToTable("registration_selection_rules", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationStatisticRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssociatedStatisticRuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_statistic_rule_id");

                    b.Property<int>("LevelRequirement")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_registration_id");

                    b.Property<string>("StackingBonus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegistrationId");

                    b.ToTable("registration_statistic_rules", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.SavingThrows.SavingThrow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AbilityScoreAbbreviation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ability_score_abbreviation");

                    b.Property<Guid>("AbilityScoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ability_score_id");

                    b.Property<int>("AbilityScoreModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ability_score_modifier");

                    b.Property<int>("AdditionalBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("additional_bonus");

                    b.Property<Guid>("AssociatedRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_registration_id");

                    b.Property<int>("CalculatedBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("calculated_bonus");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("parent_component_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedRegistrationId");

                    b.HasIndex("parent_component_id");

                    b.ToTable("savingthrows", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AbilityScoreAbbreviation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ability_score_abbreviation");

                    b.Property<Guid>("AbilityScoreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ability_score_id");

                    b.Property<int>("AbilityScoreModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("ability_score_modifier");

                    b.Property<int>("AdditionalBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("additional_bonus");

                    b.Property<Guid>("AssociatedRegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("associated_registration_id");

                    b.Property<int>("CalculatedBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("calculated_bonus");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid>("parent_component_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedRegistrationId");

                    b.HasIndex("parent_component_id");

                    b.ToTable("skills", "characters");
                });

            modelBuilder.Entity("Starlights.Platform.Components.Data.EntityFramework.EventMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("event_messages", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Abilities.AbilitiesComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase");

                    b.ToTable("component_abilities", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Appearances.AppearanceComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase");

                    b.Property<string>("PortraitUrl")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("component_appearance", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Classes.ClassComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase");

                    b.ToTable("component_class", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Progression.ProgressionComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase");

                    b.Property<int>("CharacterLevel")
                        .HasColumnType("int")
                        .HasColumnName("character_level");

                    b.ToTable("component_progression", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.SavingThrows.SavingThrowsComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase");

                    b.ToTable("component_saving_throws", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Skills.SkillsComponent", b =>
                {
                    b.HasBaseType("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase");

                    b.ToTable("component_skills", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Abilities.AbilityScore", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Abilities.AbilitiesComponent", null)
                        .WithMany("AbilityScores")
                        .HasForeignKey("parent_component_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Classes.CharacterClass", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Classes.ClassComponent", null)
                        .WithMany("Classes")
                        .HasForeignKey("parent_component_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Components.CharacterComponentBase", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("Components")
                        .HasForeignKey("ParentCharacter")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationIncludeRule", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Registrations.Registration", null)
                        .WithMany("IncludeRules")
                        .HasForeignKey("ParentRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationSelectionRule", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Registrations.Registration", null)
                        .WithMany("SelectionRules")
                        .HasForeignKey("ParentRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationStatisticRule", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Registrations.Registration", null)
                        .WithMany("StatisticRules")
                        .HasForeignKey("ParentRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.SavingThrows.SavingThrow", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.SavingThrows.SavingThrowsComponent", null)
                        .WithMany("SavingThrows")
                        .HasForeignKey("parent_component_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Skills.Skill", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Skills.SkillsComponent", null)
                        .WithMany("Skills")
                        .HasForeignKey("parent_component_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.Registration", b =>
                {
                    b.Navigation("IncludeRules");

                    b.Navigation("SelectionRules");

                    b.Navigation("StatisticRules");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Abilities.AbilitiesComponent", b =>
                {
                    b.Navigation("AbilityScores");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Classes.ClassComponent", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.SavingThrows.SavingThrowsComponent", b =>
                {
                    b.Navigation("SavingThrows");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Skills.SkillsComponent", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
