// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starlights.Modules.Characters.Data.EntityFramework;

#nullable disable

namespace Starlights.Modules.Characters.Data.EntityFramework.Migrations
{
    [DbContext(typeof(CharactersContext))]
    [Migration("20250819144814_AddRegistrationStatisticsRule")]
    partial class AddRegistrationStatisticsRule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("characters")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Abilities.AbilityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdditionalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("AssociatedRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BaseScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("CalculatedModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CalculatedScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedRegistrationId");

                    b.HasIndex("CharacterId");

                    b.ToTable("ability_scores", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Appearances.Appearance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PortraitUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("appearance", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("character", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssociatedElementName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AssociatedElementType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("registration", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationIncludeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedIncludeRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IncludedElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IncludedElementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegistrationId");

                    b.ToTable("registration_include_rules", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationStatisticRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedStatisticRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParentRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegistrationId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("registration_statistic_rules", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.SavingThrows.SavingThrow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AbilityScoreAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AbilityScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AbilityScoreModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AdditionalBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("AssociatedRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CalculatedBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedRegistrationId");

                    b.HasIndex("CharacterId");

                    b.ToTable("savingthrows", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AbilityScoreAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AbilityScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AbilityScoreModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AdditionalBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("AssociatedRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CalculatedBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedRegistrationId");

                    b.HasIndex("CharacterId");

                    b.ToTable("skills", "characters");
                });

            modelBuilder.Entity("Starlights.Platform.Components.Data.EntityFramework.EventMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("event_messages", "characters");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Abilities.AbilityScore", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("AbilityScores")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationIncludeRule", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Registrations.Registration", null)
                        .WithMany("IncludeRules")
                        .HasForeignKey("ParentRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.RegistrationStatisticRule", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Registrations.Registration", null)
                        .WithMany("StatisticRules")
                        .HasForeignKey("RegistrationId");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.SavingThrows.SavingThrow", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("SavingThrows")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Skills.Skill", b =>
                {
                    b.HasOne("Starlights.Modules.Characters.Domain.Characters.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Characters.Character", b =>
                {
                    b.Navigation("AbilityScores");

                    b.Navigation("SavingThrows");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Starlights.Modules.Characters.Domain.Registrations.Registration", b =>
                {
                    b.Navigation("IncludeRules");

                    b.Navigation("StatisticRules");
                });
#pragma warning restore 612, 618
        }
    }
}
