// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Starlights.Acceptance.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
    public partial class AbilityScoresFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "ignore"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Ability Scores", "\tAs a player\r\n\tI want the ability modifiers of my character to reflect score chan" +
                "ges\r\n\tSo that the abilities of my character are accurately represented", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AbilityScores.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
#line hidden
#line 9
 await testRunner.GivenAsync("a new character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/AbilityScores.feature.ndjson", 35);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("updated with a score increase")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("updated with a score increase")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        public async global::System.Threading.Tasks.Task UpdatedWithAScoreIncrease()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("updated with a score increase", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the ability modifier should be updated when the score changes", null, tagsOfRule);
#line 13
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 14
 await testRunner.GivenAsync("the character\'s Intelligence score is 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
 await testRunner.WhenAsync("the character\'s Intelligence score is changed to 15", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("the character\'s Intelligence modifier should be 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("updated with a score decrease")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("updated with a score decrease")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("otel")]
        public async global::System.Threading.Tasks.Task UpdatedWithAScoreDecrease()
        {
            string[] tagsOfScenario = new string[] {
                    "otel"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("updated with a score decrease", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the ability modifier should be updated when the score changes", null, tagsOfRule);
#line 19
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 20
 await testRunner.GivenAsync("the character\'s Wisdom score is 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
 await testRunner.WhenAsync("the character\'s Wisdom score is changed to 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("the character\'s Wisdom modifier should be -1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("computing the modifier for a variety of Strength scores")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("computing the modifier for a variety of Strength scores")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("1", "-5", "2", null, DisplayName="computing the modifier for a variety of Strength scores(1,-5,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("2", "-4", "3", null, DisplayName="computing the modifier for a variety of Strength scores(2,-4,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("3", "-4", "4", null, DisplayName="computing the modifier for a variety of Strength scores(3,-4,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("4", "-3", "5", null, DisplayName="computing the modifier for a variety of Strength scores(4,-3,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("5", "-3", "6", null, DisplayName="computing the modifier for a variety of Strength scores(5,-3,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("6", "-2", "7", null, DisplayName="computing the modifier for a variety of Strength scores(6,-2,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("7", "-2", "8", null, DisplayName="computing the modifier for a variety of Strength scores(7,-2,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("8", "-1", "9", null, DisplayName="computing the modifier for a variety of Strength scores(8,-1,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("9", "-1", "10", null, DisplayName="computing the modifier for a variety of Strength scores(9,-1,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("10", "0", "11", null, DisplayName="computing the modifier for a variety of Strength scores(10,0,11)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("11", "0", "12", null, DisplayName="computing the modifier for a variety of Strength scores(11,0,12)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("12", "1", "13", null, DisplayName="computing the modifier for a variety of Strength scores(12,1,13)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("13", "1", "14", null, DisplayName="computing the modifier for a variety of Strength scores(13,1,14)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("14", "2", "15", null, DisplayName="computing the modifier for a variety of Strength scores(14,2,15)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("15", "2", "16", null, DisplayName="computing the modifier for a variety of Strength scores(15,2,16)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("16", "3", "17", null, DisplayName="computing the modifier for a variety of Strength scores(16,3,17)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("17", "3", "18", null, DisplayName="computing the modifier for a variety of Strength scores(17,3,18)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("18", "4", "19", null, DisplayName="computing the modifier for a variety of Strength scores(18,4,19)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("19", "4", "20", null, DisplayName="computing the modifier for a variety of Strength scores(19,4,20)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("20", "5", "21", null, DisplayName="computing the modifier for a variety of Strength scores(20,5,21)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("21", "5", "22", null, DisplayName="computing the modifier for a variety of Strength scores(21,5,22)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("22", "6", "23", null, DisplayName="computing the modifier for a variety of Strength scores(22,6,23)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("23", "6", "24", null, DisplayName="computing the modifier for a variety of Strength scores(23,6,24)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("24", "7", "25", null, DisplayName="computing the modifier for a variety of Strength scores(24,7,25)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("25", "7", "26", null, DisplayName="computing the modifier for a variety of Strength scores(25,7,26)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("26", "8", "27", null, DisplayName="computing the modifier for a variety of Strength scores(26,8,27)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("27", "8", "28", null, DisplayName="computing the modifier for a variety of Strength scores(27,8,28)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("28", "9", "29", null, DisplayName="computing the modifier for a variety of Strength scores(28,9,29)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("29", "9", "30", null, DisplayName="computing the modifier for a variety of Strength scores(29,9,30)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("30", "10", "31", null, DisplayName="computing the modifier for a variety of Strength scores(30,10,31)")]
        public async global::System.Threading.Tasks.Task ComputingTheModifierForAVarietyOfStrengthScores(string score, string modifier, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Score", score);
            argumentsOfScenario.Add("Modifier", modifier);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("computing the modifier for a variety of Strength scores", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the ability modifier should follow the standard formula (score - 10) / 2 rounded " +
                    "down", null, tagsOfRule);
#line 26
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 27
 await testRunner.GivenAsync("the character\'s Strength score is 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
 await testRunner.WhenAsync(string.Format("the character\'s Strength score is changed to {0}", score), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
 await testRunner.ThenAsync(string.Format("the character\'s Strength modifier should be {0}", modifier), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("attempting to set an ability score above the maximum")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("attempting to set an ability score above the maximum")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("wip")]
        public async global::System.Threading.Tasks.Task AttemptingToSetAnAbilityScoreAboveTheMaximum()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "32";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("attempting to set an ability score above the maximum", null, tagsOfScenario, argumentsOfScenario, global::Reqnroll.TagHelper.CombineTags(featureTags, new string[] {
                            "ignore",
                            "wip"}), pickleIndex);
            string[] tagsOfRule = new string[] {
                    "ignore",
                    "wip"};
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("the ability score maximum value for a new character is capped at 20", null, tagsOfRule);
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await this.FeatureBackgroundAsync();
#line hidden
#line 68
 await testRunner.GivenAsync("the character\'s Charisma score is 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
 await testRunner.WhenAsync("the character\'s Charisma score is changed to 22", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
    await testRunner.ThenAsync("the character\'s Charisma score should be 20", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 71
    await testRunner.AndAsync("the character\'s Charisma modifier should be 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
