// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Starlights.Acceptance.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AbilityScoresFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Ability Scores", "\tAs a player\r\n\tI want the ability modifiers of my character to reflect score chan" +
                "ges\r\n\tSo that the abilities of my character are accurately represented", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "AbilityScores.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
 await testRunner.GivenAsync("a new character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("updated with a score increase")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        public async System.Threading.Tasks.Task UpdatedWithAScoreIncrease()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("updated with a score increase", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 13
 await testRunner.GivenAsync("the character\'s Intelligence score is 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
 await testRunner.WhenAsync("the character\'s Intelligence score is changed to 15", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("the character\'s Intelligence modifier should be 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("updated with a score decrease")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("otel")]
        public async System.Threading.Tasks.Task UpdatedWithAScoreDecrease()
        {
            string[] tagsOfScenario = new string[] {
                    "otel"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("updated with a score decrease", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 19
 await testRunner.GivenAsync("the character\'s Wisdom score is 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
 await testRunner.WhenAsync("the character\'s Wisdom score is changed to 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("the character\'s Wisdom modifier should be -1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("computing the modifier for a variety of Strength scores")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("1", "-5", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("2", "-4", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("3", "-4", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("4", "-3", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("5", "-3", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("6", "-2", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("7", "-2", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("8", "-1", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("9", "-1", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("10", "0", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("11", "0", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("12", "1", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("13", "1", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("14", "2", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("15", "2", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("16", "3", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("17", "3", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("18", "4", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("19", "4", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("20", "5", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("21", "5", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("22", "6", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("23", "6", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("24", "7", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("25", "7", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("26", "8", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("27", "8", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("28", "9", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("29", "9", null)]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("30", "10", null)]
        public async System.Threading.Tasks.Task ComputingTheModifierForAVarietyOfStrengthScores(string score, string modifier, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Score", score);
            argumentsOfScenario.Add("Modifier", modifier);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("computing the modifier for a variety of Strength scores", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 26
 await testRunner.GivenAsync("the character\'s Strength score is 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
 await testRunner.WhenAsync(string.Format("the character\'s Strength score is changed to {0}", score), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
 await testRunner.ThenAsync(string.Format("the character\'s Strength modifier should be {0}", modifier), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("attempting to set an ability score above the maximum")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Ability Scores")]
        public async System.Threading.Tasks.Task AttemptingToSetAnAbilityScoreAboveTheMaximum()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("attempting to set an ability score above the maximum", null, tagsOfScenario, argumentsOfScenario, TagHelper.CombineTags(featureTags, new string[] {
                            "ignore",
                            "wip"}));
#line 66
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 67
 await testRunner.GivenAsync("the character\'s Charisma score is 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
 await testRunner.WhenAsync("the character\'s Charisma score is changed to 22", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
    await testRunner.ThenAsync("the character\'s Charisma score should be 20", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 70
    await testRunner.AndAsync("the character\'s Charisma modifier should be 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
