// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Starlights.Integration.Acceptance.Tests.Features.Content
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ContentManagementForSpellsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Content", "Content management for spells", "As a content creator\r\nI want to create, update, delete and list spells\r\nSo that p" +
                "layers can use those spells during character creation", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "manage-spells.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
    await testRunner.GivenAsync("I am authenticated as a content creator", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Content/manage-spells.feature.ndjson", 19);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a spell with the minimum required fields")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a spell with the minimum required fields")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateASpellWithTheMinimumRequiredFields()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a spell with the minimum required fields", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells with the minimum required fields", null, tagsOfRule);
#line 14
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration"});
                table1.AddRow(new string[] {
                            "Magic Spell",
                            "0",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "Instantaneous"});
#line 15
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table1, "When ");
#line hidden
#line 18
    await testRunner.ThenAsync("the spell appears in the spell list with all provided properties", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a spell with a specific level")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a spell with a specific level")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Evocation cantrip", "0", "Evocation", "1 bonus action", "10 ft", "Instantaneous", "1", null, DisplayName="create a spell with a specific level(Evocation cantrip,0,Evocation,1 bonus action" +
            ",10 ft,Instantaneous,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("1st-level necromancy spell", "1", "Necromancy", "1 action", "Touch", "1 minute", "2", null, DisplayName="create a spell with a specific level(1st-level necromancy spell,1,Necromancy,1 ac" +
            "tion,Touch,1 minute,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("9th-level abjuration spell", "9", "Abjuration", "1 action", "30 ft", "Concentration, up to 1 minute", "3", null, DisplayName="create a spell with a specific level(9th-level abjuration spell,9,Abjuration,1 ac" +
            "tion,30 ft,Concentration, up to 1 minute,3)")]
        public async global::System.Threading.Tasks.Task CreateASpellWithASpecificLevel(string name, string level, string magicSchool, string castingTime, string range, string duration, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("level", level);
            argumentsOfScenario.Add("magic school", magicSchool);
            argumentsOfScenario.Add("casting time", castingTime);
            argumentsOfScenario.Add("range", range);
            argumentsOfScenario.Add("duration", duration);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a spell with a specific level", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells up to level 9", null, tagsOfRule);
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration"});
                table2.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", level),
                            string.Format("{0}", magicSchool),
                            string.Format("{0}", castingTime),
                            string.Format("{0}", range),
                            string.Format("{0}", duration)});
#line 23
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table2, "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("the spell appears in the spell list with all provided properties", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a concentration spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a concentration spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateAConcentrationSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a concentration spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells that require concentration", null, tagsOfRule);
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration",
                            "concentration"});
                table3.AddRow(new string[] {
                            "Magic Spell",
                            "5",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "Concentration, up to 10 minutes",
                            "true"});
#line 37
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table3, "When ");
#line hidden
#line 40
    await testRunner.ThenAsync("the spell appears in the spell list as a concentration spell", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a ritual spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a ritual spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateARitualSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a ritual spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells that can be cast as rituals", null, tagsOfRule);
#line 44
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration",
                            "ritual"});
                table4.AddRow(new string[] {
                            "Magic Spell",
                            "5",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "1 hour",
                            "true"});
#line 45
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table4, "When ");
#line hidden
#line 48
    await testRunner.ThenAsync("the spell appears in the spell list as a ritual spell", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a spell with a somatic component")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a spell with a somatic component")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateASpellWithASomaticComponent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a spell with a somatic component", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells that require a combination of somatic, verbal" +
                    ", and material components", null, tagsOfRule);
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration",
                            "somatic"});
                table5.AddRow(new string[] {
                            "Magic Spell",
                            "5",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "1 hour",
                            "true"});
#line 53
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table5, "When ");
#line hidden
#line 56
    await testRunner.ThenAsync("the spell appears in the spell list as having a somatic component", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a spell with a verbal component")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a spell with a verbal component")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateASpellWithAVerbalComponent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a spell with a verbal component", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells that require a combination of somatic, verbal" +
                    ", and material components", null, tagsOfRule);
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration",
                            "verbal"});
                table6.AddRow(new string[] {
                            "Magic Spell",
                            "5",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "1 hour",
                            "true"});
#line 59
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table6, "When ");
#line hidden
#line 62
    await testRunner.ThenAsync("the spell appears in the spell list as having a verbal component", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a spell with a material component")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a spell with a material component")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateASpellWithAMaterialComponent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a spell with a material component", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells that require a combination of somatic, verbal" +
                    ", and material components", null, tagsOfRule);
#line 64
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration",
                            "material",
                            "material components"});
                table7.AddRow(new string[] {
                            "Magic Spell",
                            "5",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "1 hour",
                            "true",
                            "a small crystal rod"});
#line 65
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table7, "When ");
#line hidden
#line 68
    await testRunner.ThenAsync("the spell appears in the spell list as having a material component with the provi" +
                        "ded material components description", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a spell with a description")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a spell with a description")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateASpellWithADescription()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a spell with a description", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells with detailed descriptions", null, tagsOfRule);
#line 72
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration",
                            "description"});
                table8.AddRow(new string[] {
                            "Magic Spell",
                            "5",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "1 hour",
                            "A powerful evocation spell that deals damage."});
#line 73
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table8, "When ");
#line hidden
#line 76
    await testRunner.ThenAsync("the spell appears in the spell list with the provided description", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="create a spell with a markdown description")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("create a spell with a markdown description")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task CreateASpellWithAMarkdownDescription()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("create a spell with a markdown description", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can create spells with detailed descriptions", null, tagsOfRule);
#line 78
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 79
    await testRunner.GivenAsync("the content creator prepared the following markdown description", @"You create an acidic bubble at a point within range,
where it explodes in a 5-foot-radius Sphere. Each
creature in that Sphere must succeed on a Dexterity
saving throw or take 1d6 Acid damage.
__Cantrip Upgrade.__ The damage increases by 1d6
when you reach levels 5 (2d6), 11 (3d6), and 17
(4d6).", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration",
                            "description"});
                table9.AddRow(new string[] {
                            "Fireball",
                            "3",
                            "Evocation",
                            "1 action",
                            "150 ft",
                            "Instantaneous",
                            "<markdown description>"});
#line 89
    await testRunner.WhenAsync("the content creator creates a spell with the following properties", ((string)(null)), table9, "When ");
#line hidden
#line 92
    await testRunner.ThenAsync("the spell appears in the spell list with the provided description", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="update the required fields of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("update the required fields of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task UpdateTheRequiredFieldsOfAnExistingSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("update the required fields of an existing spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can update existing spells", null, tagsOfRule);
#line 98
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration"});
                table10.AddRow(new string[] {
                            "Level 3 Spell",
                            "3",
                            "Evocation",
                            "1 action",
                            "100 ft",
                            "1 minute"});
#line 99
    await testRunner.GivenAsync("a spell exists that includes the following properties", ((string)(null)), table10, "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration"});
                table11.AddRow(new string[] {
                            "Level 6 Spell",
                            "6",
                            "Conjuration",
                            "1 bonus action",
                            "200 ft",
                            "2 minutes"});
#line 102
    await testRunner.WhenAsync("the content creator updates the spell with the following properties", ((string)(null)), table11, "When ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "level",
                            "magic school",
                            "casting time",
                            "range",
                            "duration"});
                table12.AddRow(new string[] {
                            "Level 6 Spell",
                            "6",
                            "Conjuration",
                            "1 bonus action",
                            "200 ft",
                            "2 minutes"});
#line 105
    await testRunner.ThenAsync("the spell in the spell list should have the following properties", ((string)(null)), table12, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="update a non concentration spell to a concentration spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("update a non concentration spell to a concentration spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task UpdateANonConcentrationSpellToAConcentrationSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("update a non concentration spell to a concentration spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can update existing spells", null, tagsOfRule);
#line 109
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "duration",
                            "concentration"});
                table13.AddRow(new string[] {
                            "Instant Spell",
                            "Instantaneous",
                            "false"});
#line 110
    await testRunner.GivenAsync("a spell exists that includes the following properties", ((string)(null)), table13, "Given ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "duration",
                            "concentration"});
                table14.AddRow(new string[] {
                            "Concentrating Spell",
                            "Concentration, up to 1 minute",
                            "true"});
#line 113
    await testRunner.WhenAsync("the content creator updates the spell with the following properties", ((string)(null)), table14, "When ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "duration",
                            "concentration"});
                table15.AddRow(new string[] {
                            "Concentrating Spell",
                            "Concentration, up to 1 minute",
                            "true"});
#line 116
    await testRunner.ThenAsync("the spell in the spell list should have the following properties", ((string)(null)), table15, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="update a non ritual spell to a ritual spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("update a non ritual spell to a ritual spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task UpdateANonRitualSpellToARitualSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("update a non ritual spell to a ritual spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can update existing spells", null, tagsOfRule);
#line 120
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "ritual"});
                table16.AddRow(new string[] {
                            "Quick Spell",
                            "false"});
#line 121
    await testRunner.GivenAsync("a spell exists that includes the following properties", ((string)(null)), table16, "Given ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "ritual"});
                table17.AddRow(new string[] {
                            "Ritual Spell",
                            "true"});
#line 124
    await testRunner.WhenAsync("the content creator updates the spell with the following properties", ((string)(null)), table17, "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "ritual"});
                table18.AddRow(new string[] {
                            "Ritual Spell",
                            "true"});
#line 127
    await testRunner.ThenAsync("the spell in the spell list should have the following properties", ((string)(null)), table18, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="update a components of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("update a components of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task UpdateAComponentsOfAnExistingSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("update a components of an existing spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can update existing spells", null, tagsOfRule);
#line 131
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "verbal",
                            "somatic",
                            "material"});
                table19.AddRow(new string[] {
                            "Free Spell",
                            "false",
                            "false",
                            "false"});
#line 132
    await testRunner.GivenAsync("a spell exists that includes the following properties", ((string)(null)), table19, "Given ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "verbal",
                            "somatic",
                            "material",
                            "material components"});
                table20.AddRow(new string[] {
                            "Component Spell",
                            "true",
                            "true",
                            "true",
                            "a black feather"});
#line 135
    await testRunner.WhenAsync("the content creator updates the spell with the following properties", ((string)(null)), table20, "When ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "verbal",
                            "somatic",
                            "material",
                            "material components"});
                table21.AddRow(new string[] {
                            "Component Spell",
                            "true",
                            "true",
                            "true",
                            "a black feather"});
#line 138
    await testRunner.ThenAsync("the spell in the spell list should have the following properties", ((string)(null)), table21, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="update the description of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("update the description of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task UpdateTheDescriptionOfAnExistingSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("update the description of an existing spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can update existing spells", null, tagsOfRule);
#line 142
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "description"});
                table22.AddRow(new string[] {
                            "Cryptic Spell",
                            "You cast a spell."});
#line 143
    await testRunner.GivenAsync("a spell exists that includes the following properties", ((string)(null)), table22, "Given ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "description"});
                table23.AddRow(new string[] {
                            "Descriptive Spell",
                            "You cast a very detailed spell."});
#line 146
    await testRunner.WhenAsync("the content creator updates the spell with the following properties", ((string)(null)), table23, "When ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "description"});
                table24.AddRow(new string[] {
                            "Descriptive Spell",
                            "You cast a very detailed spell."});
#line 149
    await testRunner.ThenAsync("the spell in the spell list should have the following properties", ((string)(null)), table24, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="update the markdown description of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("update the markdown description of an existing spell")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Content management for spells")]
        public async global::System.Threading.Tasks.Task UpdateTheMarkdownDescriptionOfAnExistingSpell()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("update the markdown description of an existing spell", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A content creator can update existing spells", null, tagsOfRule);
#line 153
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 154
    await testRunner.GivenAsync("the content creator prepared the following markdown description", "You create a very details markdown spell description\r\nthat spans multiple lines.\r" +
                        "\n__Description Upgrade.__ The description increase by 1d6\r\nwhen you reach levels" +
                        " 5 (2d6), 11 (3d6), and 17\r\n(4d6).", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "description"});
                table25.AddRow(new string[] {
                            "Simple Spell",
                            "You create a simple spell."});
#line 162
    await testRunner.AndAsync("a spell exists that includes the following properties", ((string)(null)), table25, "And ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "description"});
                table26.AddRow(new string[] {
                            "Markdown Spell",
                            "<markdown description>"});
#line 165
    await testRunner.WhenAsync("the content creator updates the spell with the following properties", ((string)(null)), table26, "When ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "description"});
                table27.AddRow(new string[] {
                            "Markdown Spell",
                            "<markdown description>"});
#line 168
    await testRunner.ThenAsync("the spell in the spell list should have the following properties", ((string)(null)), table27, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
