name: CI/CD - Development

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: "9.0.x"

jobs:
  build-solution:
    name: Build & Test Solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Solution
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build
